apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconstruct-deployment
  labels:
    app: reconstruct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconstruct
  template:
    metadata:
      labels:
        app: reconstruct
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "reconstruct"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"

    spec:
      containers:
      - name: reconstruct
        image: reconstruct:latest
        imagePullPolicy: Never

