apiVersion: apps/v1
kind: Deployment
metadata:
  name: vesseldetector-deployment
  labels:
    app: vesseldetector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vesseldetector
  template:
    metadata:
      labels:
        app: vesseldetector
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "vesseldetector"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
    spec:
      containers:
      - name: vessel-detector
        image: vessel-detector:latest
        imagePullPolicy: Never